package main

// “Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, …
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.”

import "fmt"

func main() {
	a := 0
	b := 1
	const max = 4_000_000
	sum := 0

	for b < max {
		if b%2 == 0 {
			sum = sum + b
		}
		a, b = b, b+a
	}

	fmt.Println(sum)
}
